### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1:

### ISSUE THREAD

**Issue by Siddharth-chauhan** [payu-intrepos/iOS-SDK-Swift#1]
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1
can you please create new framework with swift 4.1

**Comment by tech4solitude** [comment]
@AshishPayU any update on this ??

**Comment by AshishPayU** [comment]
Hi, 

The issue has already been sorted out weeks back with the last release support latest Swift Version.
Please refer below link:
https://github.com/payu-intrepos/iOS-SDK-Swift/releases

**Comment by AshishPayU** [comment]
closed.

**Comment by Siddharth-chauhan** [comment]
@AshishPayU thank you brother.

**Comment by elitelokesh** [comment]
Not resolved
