### ISSUE TITLE
Please update for Swift5

### ISSUE THREAD

**Issue by pranshudunzo** [payu-intrepos/iOS-SDK-Swift#11]

**Comment by ragzy15** [comment]
please add swift 5 support

**Comment by SaadIEng** [comment]
@pranshudunzo and @ragzy15 are you facing any issue?? When running for Xcode 10.2 with swift 5??

**Comment by SaadIEng** [comment]
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler:

**Comment by subhadeep-pal** [comment]
Yes facing the same issue

**Comment by subhadeep-pal** [comment]
are not able to test on physical devices if they upgrade to iOS v12.2 as Xcode 10.2 is required to build and test on them

**Comment by SaadIEng** [comment]
@subhadeep-pal I have downloaded the Xcode 10.1 as I my Xcode updated to version 10.2, and it's working fine now.

**Comment by subhadeep-pal** [comment]
> @subhadeep-pal I have downloaded the Xcode 10.1 as I my Xcode updated to version 10.2, and it's working fine now.

can you elaborate?

**Comment by subhadeep-pal** [comment]
any update guys?

**Comment by nagarro-mohitpadalia** [comment]
@subhadeep-pal 

Please check the latest version, its updated for Swift 5.0

**Comment by subhadeep-pal** [comment]
Thanks a lot, just saw the release

**Comment by DishaMukherjee** [comment]
closed.
