### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/apple/Downloads/iOS-SDK-Sample-App-Swift-SampleApp1.1 2/Tar_SampleApp1.1/iOS-SDK-Sample-App-Swift-SampleApp1.0 2/PayU_SampleApp_Swift1.0/PayU/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by maheshlantech** [payu-intrepos/iOS-SDK-Swift#13]

**Comment by maheshlantech** [comment]
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/apple/Downloads/iOS-SDK-Sample-App-Swift-SampleApp1.1 2/Tar_SampleApp1.1/iOS-SDK-Sample-App-Swift-SampleApp1.0 2/PayU_SampleApp_Swift1.0/PayU/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64.swiftmodule

**Comment by subhadeep-pal** [comment]
Any resolution on this ?

**Comment by maheshlantech** [comment]
import PayU_coreSDK_Swift (showing error)
PayU_coreSDK_Swift SDK NOT support

**Comment by subhadeep-pal** [comment]
Any update?

**Comment by DishaMukherjee** [comment]
Hi Subhadeep, 

It is already released, please see our github repo.

**Comment by yulubike** [comment]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/purnendu/Desktop/yulu/ios-customer-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule


Please help us on solving this issue

**Comment by yulubike** [comment]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/purnendu/Desktop/yulu/ios-customer-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

using Xcode 11.2.1 and seeing this issue.

**Comment by yulubike** [comment]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/Apple/Desktop/ios-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

using Xcode 11.2.1 and seeing this issue. Please help us solving this issue.

**Comment by purnendu-roy** [comment]
"PayU_coreSDK_Swift "
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler: /Users/purnendu/Documents/Projects/ios-customer-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/arm64-apple-ios.swiftmodule

any update on this issue ?

**Comment by purnendu-roy** [comment]
> Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/Apple/Desktop/ios-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
> 
> using Xcode 11.2.1 and seeing this issue. Please help us solving this issue.

Any resolution on this ?
