### ISSUE TITLE
Module not updated please update

### ISSUE THREAD

**Issue by arvind8192** [payu-intrepos/iOS-SDK-Swift#2]
Hi,
I am getting following issue after update xcode to version9.4 please help me out

module compiled with Swift 4.0.2 cannot be imported in Swift 4.1.2: /Users/webwerks/Desktop/sampledemo/./PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64.swiftmodule

**Comment by AshishPayU** [comment]
Hi Arvind,

The SDK is already updated, please replace framework in Sample app with latest one:
https://github.com/payu-intrepos/iOS-SDK-Swift/releases

**Comment by elitelokesh** [comment]
No this is not updated for the latest version
