### ISSUE TITLE
I am using  pod 'PayUBiz-coreSDK-Swift', '2.1' on Xcode11.3(Latest version) and getting Below Error.

### ISSUE THREAD

**Issue by purnendu-roy** [payu-intrepos/iOS-SDK-Swift#23]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler: /Users/Apple/Documents/Projects/ios-app/Pods/PayUBiz-coreSDK-Swift/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/arm64-apple-ios.swiftmodule.

**Comment by DishaMukherjee** [comment]
hey Purnendu,

Can you please try clearing Pod cache & check.

**Comment by purnendu-roy** [comment]
@DishaMukherjee still the issue persists. Help me solve this issue.

I have tried all these.
pod cache clean --all

rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install

**Comment by Simran-iOS** [comment]
It’s working, make sure you have updated your Xcode, pod.

Alternatively, you can download it from below which is same as Pod:
https://github.com/payu-intrepos/iOS-SDK-Swift/releases
