### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50 . - Xcode 10 error

### ISSUE THREAD

**Issue by tech4solitude** [payu-intrepos/iOS-SDK-Swift#3]
@AshishPayU  - can you please update this. 
we're facing Module compiled with Swift 4.1 cannot be imported in Swift 4.1.50 error in Xcode 10 beta

**Comment by tech4solitude** [comment]
@AshishPayU any update on this

**Comment by AshishPayU** [comment]
Hi, 
We are not supporting Beta version of X-Code for the build, please use v9.4.1 .
