### ISSUE TITLE
When importing in VC showing module error- Xcode 9.4.1

### ISSUE THREAD

**Issue by Vaibhav43** [payu-intrepos/iOS-SDK-Swift#4]
Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1.2: /Users/vaibhavagarwal/Documents/iOS/demo/PayBiz/PayBiz/PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64.swiftmodule

**Comment by paulmtech** [comment]
Please help me how fix this issue.

Module compiled with Swift 4.0.2 cannot be imported by the Swift 4.2 compiler: /......./PayU_coreSDK_Swift.framework/Modules/PayU_coreSDK_Swift.swiftmodule/x86_64.swiftmodule

**Comment by AshishPayU** [comment]
Please check with our latest release.

**Comment by elitelokesh** [comment]
Not working with the latest release
