### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported by the Swift 4.2.1 compiler: 

### ISSUE THREAD

**Issue by elitelokesh** [payu-intrepos/iOS-SDK-Swift#9]
Module compiled with Swift 4.0.3 cannot be imported by the Swift 4.2.1 compiler:

Please fix this **issue** and provide a **pod** update too.
I have even contacted the support team multiple times but no resolution received from the support team.

@AshishPayU

**Comment by DishaMukherjee** [comment]
Hi Lokesh,

We have already updated our SDK to support latest Swift version, pls refer below doc and update framework:
https://github.com/payu-intrepos/iOS-SDK-Swift/releases

**Comment by samarth-ms** [comment]
The iOS SDK Swift v1.3 Sample App still has this issue although it works fine on integrating with my app. I'm unable to run the sample.
@DishaMukherjee, @AshishPayU could you please help me with this.

**Comment by samarth-ms** [comment]
Fixed it. Apparently XCode was referencing the wrong file even after updating the SDK in the sample app with the latest one. But even after fixing that I had quite a few issues with the sample. Please fix them as we don't have any other documentation available.

**Comment by SaadIEng** [comment]
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

**Comment by DishaMukherjee** [comment]
already released two versions post to that.
